---
# tasks file for base_image
- name: Ensure requirements in place
  package:
    name:
      - guestfs-tools
#- python3-libvirt
    state: present
  become: yes

- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no

- meta: end_play
  when: "vm_name in existing_vms.list_vms"

- name: Create VM if not exists
  block:
    - name: Create temporary template file
      ansible.builtin.tempfile:
        state: file
        suffix: temp
      register: ks_file

    - name: Copying
      copy:
        content: "{{ lookup('template', 'desktop.ks.j2') }}"
        dest: "{{ ks_file.path }}"

    - name: OS Install
      command: |
        virt-install \
        --name {{ vm_name }} \
        --memory {{ vm_ram_mb }} --vcpus {{ vm_vcpus }} --disk size={{ vm_disk_size}}
        --location {{ kernel_location }} \
        --initrd-inject {{ ks_file.path }} \
        --extra-args=inst.ks=file:/{{ ks_file.path | basename }} \
        --noautoconsole \
        --wait \

- name: Shutdown Machine
  command:
    virsh destroy {{ vm_name }}

- name: Replace configuration xml
  block:
    - name: Create temporary xml file
      ansible.builtin.tempfile:
        state: file
        suffix: temp
      register: xml_file

    - name: Copying xml template
      copy:
        content: "{{ lookup('template', 'base.xml.j2') }}"
        dest: "{{ xml_file.path }}"

    - name: Undefine vm
      command: |
        virsh undefine {{ vm_name }}

    - name: Define new xml
      command: |
        virsh define {{ xml_file.path }}
