---
# tasks file for base_image
- name: Ensure requirements in place
  package:
    name:
      - guestfs-tools
      - python3-libvirt
    state: present
  become: yes

- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no

- name: Create VM if not exists
  block:
    - name: Delete existing vm
      community.libvirt.virt:
        command: undefine
        name: "{{ vm_name }}"
        force: true
      when: "vm_name in existing_vms.list_vms"

    - name: Deleting remaining images
      command: |
        rm {{ libvirt_pool_dir }}/{{ vm_name }}.qcow2
      when: "vm_name in existing_vms.list_vms"

    - name: Create temporary template file
      ansible.builtin.tempfile:
        state: file
        suffix: temp
      register: ks_file

    - name: Copying
      copy:
        content: "{{ lookup('template', 'desktop.ks.j2') }}"
        dest: "{{ ks_file.path }}"

    - name: OS Install
      command: |
        virt-install \
        --name {{ vm_name }} \
        --memory {{ vm_ram_mb }} --vcpus {{ vm_vcpus }} --disk size={{ vm_disk_size}}
        --location {{ kernel_location }} \
        --initrd-inject {{ ks_file.path }} \
        --extra-args=inst.ks=file:/{{ ks_file.path | basename }} \
        --noautoconsole \
        --wait \
