---
# tasks file for base_image
- name: Ensure requirements in place
  package:
    name:
      - guestfs-tools
      - python3-libvirt
    state: present
  become: yes

- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no

- name: Update image
  command: |
    virt-customize -d {{ item }} --selinux-relabel
    --update
  when: "item in existing_vms.list_vms"
  loop: "{{ image_list }}"
