---
# tasks file for base_image
- name: Ensure requirements in place
  package:
    name:
      - guestfs-tools
      - python3-libvirt
    state: present
  become: yes

- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no

- name: Update image
  command: |
    virt-customize -d {{ item }} --selinux-relabel
    --update
  when: "item in existing_vms.list_vms"
  loop: "{{ image_list }}"
  register: _update_result
  async: 1200
  poll: 0

- name: Wait for updates to complete
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: _jobs
  until: _jobs.finished
  retries: 1200
  delay: 1
  loop: "{{ _update_result.results }}"
