- name: Configure lab
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    pool_dir: "/var/lib/libvirt/images"
    fedora_ver: 40
    repo_mirrorlist: "https://mirrors.fedoraproject.org/metalink?repo=fedora-{{ fedora_ver }}&arch=x86_64"
    updates_mirrorlist: "https://mirrors.fedoraproject.org/metalink?repo=updates-released-f{{ fedora_ver }}&arch=x86_64"
    url_mirrorlist: "https://mirrors.fedoraproject.org/metalink?repo=fedora-{{ fedora_ver }}&arch=x86_64"
    location: "https://download.fedoraproject.org/pub/fedora/linux/releases/{{ fedora_ver }}/Everything/x86_64/os/"
    vm: "f{{ fedora_ver }}-base"
    vcpus: 4
    ram_mb: 4096
    disk_size_gb: 20
    packages: |-
    _images:
      study:
        packages: |-
        base: "f{{ fedora_ver }}-base"
        new: "f{{ fedora_ver }}-study"
        user: "user"
        hostname: "study"
      development:
        packages: |-
        base: "f{{ fedora_ver }}-base"
        new: "f{{ fedora_ver }}-development"
        user: "user"
        hostname: "development"
      pentest:
        packages: |-
          nmap
          openvpn
          wireshark
          hashcat
          ffuf
          freerdp
        base: "f{{ fedora_ver }}-base"
        new: "f{{ fedora_ver }}-pentest"
        user: "user"
        hostname: "pentest"
      personal:
        packages: |-
          libreoffice
        base: "f{{ fedora_ver }}-base"
        new: "f{{ fedora_ver }}-personal"
        user: "user"
        hostname: "personal"
      random:
        packages: |-
        base: "f{{ fedora_ver }}-base"
        new: "f{{ fedora_ver }}-random"
        user: "user"
        hostname: "random"

  tasks:
    - name: KVM Provision role
      include_role:
        name: base_image
      vars:
        libvirt_pool_dir: "{{ pool_dir }}"
        main_repo_mirrorlist: "{{ repo_mirrorlist }}"
        main_updates_mirrorlist: "{{ updates_mirrorlist }}"
        main_url_mirrorlist: "{{ url_mirrorlist }}"
        vm_name: "{{ vm }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_disk_size: "{{ disk_size_gb }}"
        additional_packages: "{{ packages }}"
        kernel_location: "{{ location }}"

    - name: Custom image role
      include_role:
        name: custom_image
      vars:
        hostname: "{{ image.value.hostname }}"
        base: "{{ image.value.base }}"
        new: "{{ image.value.new }}"
        packages: {{ image.value.packages }}
      loop: "{{ _images | dict2items }}"
      loop_control:
        loop_var: image

    - name: Custom image role
      include_role:
        name: custom_configurations
      vars:
        vm: "{{ image.value.new }}"
        user: "{{ image.value.user }}"
      loop: "{{ _images | dict2items }}"
      loop_control:
        loop_var: image
