- name: Custom images
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    packages: |-
    _images:
      development:
        packages: |-
        base: "f40-base"
        new: "f40-development"
        user: "user"
        hostname: "development"
      pentest:
        packages: |-
          nmap
          openvpn
          wireshark
          hashcat
          ffuf
          freerdp
        base: "f40-base"
        new: "f40-pentest"
        user: "user"
        hostname: "pentest"
      personal:
        packages: |-
          libreoffice
        base: "f40-base"
        new: "f40-personal"
        user: "user"
        hostname: "personal"
      random:
        packages: |-
        base: "f40-base"
        new: "f40-random"
        user: "user"
        hostname: "random"

  tasks:
    - name: Custom image role
      include_role:
        name: custom_image
      vars:
        hostname: "{{ image.value.hostname }}"
        base: "{{ image.value.base }}"
        new: "{{ image.value.new }}"
        packages: "{{ image.value.packages }}"
      loop: "{{ _images | dict2items }}"
      loop_control:
        loop_var: image
