- name: Compile vanilla linux kernel
  hosts: localhost
  gather_facts: yes
  vars:
    vm: f39-base
    major: 5
    minor: 4
    revision: 1
#checksum: "26022f2e5852ee7e3c7d17fd89d21b9c5470dbe030bcef53458c5da74f82d62d" 5.4.200
    checksum: "91d881c9aca310dc2b0534cb20552cd03ac5d6f62dcb7f88eb7add793318d0dc"
    cores: 16
    override: true
    dir: "/home/james/kvmlab/linux_kernel"

  tasks:
    - name: Kernel compilation role
      include_role:
        name: kernel_compilation
      vars:
        vm_name: "{{ vm }}"
        major_version: "{{ major }}"
        minor_version: "{{ minor }}"
        revision_version: "{{ revision }}"
        kernel_version: "{{ major }}.{{ minor }}.{{ revision }}"
        kernel_checksum: "{{ checksum }}"
        cpus: "{{ cores }}"
        override_download: "{{ override }}"
        override_folder: "{{ override }}"
        override_config: "{{ override }}"
        base_dir: "{{ dir }}"
