- name: Update images
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    images:
      - f40-base
      - f40-development
      - f40-pentest
      - f40-personal
      - f40-random
      - f40-study

  tasks:
    - name: Update image role
      include_role:
        name: update_image
      loop: "{{ images }}"
      loop_control:
        loop_var: image
