- name: Update images
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    _image_list:
      - f39-base
      - f39-personal
      - f39-pentest
      - f39-development

  tasks:
    - name: Update image role
      include_role:
        name: update_image
      vars:
        image_list: "{{ _image_list }}"
