---
# defaults file for base_image
vm_name: linux
major_version: 5
minor_version: 4
revision_version: 1
kernel_version: 5.4.1
kernel_checksum: "91d881c9aca310dc2b0534cb20552cd03ac5d6f62dcb7f88eb7add793318d0dc"
localversion: "james"
cpus: 1
override_download: false
override_folder: false
override_config: false
base_dir: "/tmp"
