---
- name: Firefox Configuration
  block:
    - name: Copy autoconfig.js
      command: |
        virt-copy-in -d {{ vm }} {{ item }} /usr/lib64/firefox/defaults/pref/
      with_fileglob:
        - ../templates/autoconfig.js

    - name: Copy firefox.cfg
      command: |
        virt-copy-in -d {{ vm }} {{ item }} /usr/lib64/firefox/
      with_fileglob:
        - ../templates/firefox.cfg

    - name: Copy policies.json
      command: |
        virt-copy-in -d {{ vm }} {{ item }} /usr/lib64/firefox/distribution/
      with_fileglob:
        - ../templates/policies.json

  when: "vm in existing_vms.list_vms"
