---
- name: Terminal Configuration
  block:
    - name: Copy tmux.conf
      command: |
        virt-copy-in -d {{ vm }} {{ item }} /home/{{ user }}
      with_fileglob:
        - ../templates/.tmux.conf

    - name: Copy vimrc
      command: |
        virt-copy-in -d {{ vm }} {{ item }} /home/{{ user }}
      with_fileglob:
        - ../templates/.vimrc
  when: "vm in existing_vms.list_vms"
