---
- name: Terminal Configuration
  block:
    - name: Copy tmux.conf
      command: |
        virt-copy-in -d {{ image }} {{ item }} /home/{{ linux_user }}
      with_fileglob:
        - ../templates/.tmux.conf

    - name: Copy vimrc
      command: |
        virt-copy-in -d {{ image }} {{ item }} /home/{{ linux_user }}
      with_fileglob:
        - ../templates/.vimrc
  when: "image in existing_vms.list_vms"
