---
# tasks file for base_image
- name: Ensure requirements in place
  package:
    name:
      - guestfs-tools
    state: present
  become: yes

- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: no

- name: Create job list
  set_fact:
    jobs: []

- name: Create all images
  include_tasks: 'roles/custom_image/tasks/customize_image.yml'
  loop: "{{ images | dict2items }}"
  loop_control:
    loop_var: image
  when: "image.value.base in existing_vms.list_vms and
         image.value.new not in existing_vms.list_vms"

- name: Wait for all images to be created
  async_status:
    jid: "{{ _job.ansible_job_id }}"
  loop: "{{ jobs }}"
  loop_control:
    loop_var: "_job"
  register: _job_results
  until: _job_results.finished
  retries: 1800
  delay: 1
