- name: Create custom image from base
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    _images:
      development:
        packages: |-
        base: "f39-base"
        new: "f39-development"
      pentest:
        packages: |-
          nmap
          openvpn
          wireshark
          hashcat
          ffuf
          freerdp
        base: "f39-base"
        new: "f39-pentest"
      personal:
        packages: |-
        base: "f39-base"
        new: "f39-personal"
      random:
        packages: |-
        base: "f39-base"
        new: "f39-random"

  tasks:
    - name: Custom image role
      include_role:
        name: custom_image
      vars:
        images: "{{ _images }}"
